collections:
  staff:
        output: false
        order:
            - pine_needle.md
            - aspen.md
            - mve.md
            - youta_funai.md
            - taga-ilog.md
season:
    enabled: false
    src: "/images/seasons/2477.svg"
